version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Madrid"
      time: "13:37"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
