name: build-kotlin-dispatcher

on:
  workflow_dispatch:
    inputs:
      machines:
        description: 'Virtual environments.'
        default: 'ubuntu-latest'
        required: true
      gradle-args:
        description: 'Gradle args for `build` step'
        default: ''
        required: false
      gradle-args-publish-snapshot:
        description: 'Gradle args for `Publish snapshot` step'
        default: ''
        required: false

jobs:
  build:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-kotlin.yaml@main
    with:
      machines: '${{ github.event.inputs.machines }}'
      gradle-args: '${{ github.event.inputs.gradle-args }}'
      gradle-args-publish-snapshot: '${{ github.event.inputs.gradle-args-publish-snapshot }}'
      allow-github-actor-bots: false
      publish-snapshot: true
      publish-docs: true
    secrets:
      OSS_USER: '${{ secrets.OSS_USER }}'
      OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
      OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
