name: generate-version-tag

on:
  workflow_call:
    inputs:
      stage:
        description: 'Stage, one of [alpha, beta, rc, final]'
        default: 'alpha'
        required: true
        type: string
      scope:
        description: 'Scope one of [mayor, minor, patch] or empty'
        default: ''
        required: false
        type: string
    secrets:
      TOKEN_GITHUB_ACTION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Gradle build
        run: ./gradlew build -P"reckon.stage"="${{ inputs.stage }}" -P"reckon.scope"="${{ inputs.scope }}"

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Stop Gradle daemons
        run: ./gradlew --stop

  generate-tag:
    runs-on: ubuntu-latest

    needs:
      - build

    env:
      GITHUB_TOKEN: '${{ secrets.TOKEN_GITHUB_ACTION }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Set up Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set version
        id: versioning
        run: |
          ./gradlew -P"reckon.stage"="${{ inputs.stage }}" -P"reckon.scope"="${{ inputs.scope }}"
          echo "lib_version=$(cat build/versioning/version.txt)" >> $GITHUB_ENV

      - name: Patch Changelog and regenerate README badges
        run: ./gradlew patchChangelog mergeChangelog buildReadmeBadges -P"reckon.stage"="${{ inputs.stage }}" -P"reckon.scope"="${{ inputs.scope }}"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff
          git add .
          git commit -m "Publish ${{ env.lib_version }}" -a

      - name: Generate Tag
        run: ./gradlew reckonTagCreate -P"reckon.stage"="${{ inputs.stage }}" -P"reckon.scope"="${{ inputs.scope }}"

      - name: Push changes
        run: git push --follow-tags

      - name: Stop Gradle daemons
        run: ./gradlew --stop
