name: publish-kotlin-catalog

on:
  push:
    tags:
      - '**'

env:
  OSS_USER: '${{ secrets.OSS_USER }}'
  OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
  OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
  GPG_KEY_NAME: '${{ secrets.GPG_KEY_NAME }}'
  GPG_PASSPHRASE: '${{ secrets.GPG_PASSPHRASE }}'
  GPG_KEY: '${{ secrets.GPG_PRIVATE_KEY }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle build
        run: ./gradlew build

  generate-catalogs:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      max-parallel: 15
      matrix:
        range:
          - from: c
            to: c
          - from: o
            to: o
          - from: i
            to: i
          - from: a
            to: b
          - from: d
            to: h
          - from: j
            to: n
          - from: p
            to: z

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Generate Kotlin libraries catalogs
        run: ./gradlew mavenScan --repository=mavenCentral --from=${{ matrix.range.from }} --to=${{ matrix.range.to }}

      - name: Upload catalogs
        uses: actions/upload-artifact@v2
        with:
          name: catalogs-${{ matrix.range.from }}-${{ matrix.range.to }}
          path: build/catalogs

      - name: Stop Gradle daemons
        run: ./gradlew --stop

  publish-kotlin-catalog:
    runs-on: ubuntu-latest

    needs: generate-catalogs

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Download catalogs
        uses: actions/download-artifact@v2
        with:
          path: build/catalogs

      - name: Gradle build
        run: ./gradlew build

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish a release
        run: ./gradlew kotlin-catalog:publishToSonatype closeSonatypeStagingRepository -P"signing.gnupg.keyName"="${{ secrets.GPG_KEY_NAME }}" -P"signing.gnupg.passphrase"="${{ secrets.GPG_PASSPHRASE }}"

      - name: Stop Gradle daemons
        run: ./gradlew --stop
